// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH4MloBl3y7OAyJvkwB5PzigCsIENEdso',
    appId: '1:508549782502:web:4e52add8feac89f8549427',
    messagingSenderId: '508549782502',
    projectId: 'fitlife2023group1',
    authDomain: 'fitlife2023group1.firebaseapp.com',
    databaseURL: 'https://fitlife2023group1-default-rtdb.firebaseio.com',
    storageBucket: 'fitlife2023group1.appspot.com',
    measurementId: 'G-34FX2HFGKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF33QlA0QWutoT68PPEHLgGUP1Y6O-mxg',
    appId: '1:508549782502:android:e5a727fcb6a72af5549427',
    messagingSenderId: '508549782502',
    projectId: 'fitlife2023group1',
    databaseURL: 'https://fitlife2023group1-default-rtdb.firebaseio.com',
    storageBucket: 'fitlife2023group1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtfMW4fd1YTsC0C7oOAeStpy0X9S0dNCE',
    appId: '1:508549782502:ios:e1e8a37c91f53172549427',
    messagingSenderId: '508549782502',
    projectId: 'fitlife2023group1',
    databaseURL: 'https://fitlife2023group1-default-rtdb.firebaseio.com',
    storageBucket: 'fitlife2023group1.appspot.com',
    iosClientId: '508549782502-ua1svpv6ea4vbbn87a7j4l5gakhok2kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitlife',
  );
}
